### ISSUE TITLE
.deb server package fails to install due to missing directory, and then places static HTML files in different directory to default cvdir but clearview-server.service does not specify this

### ISSUE THREAD

**Issue by tm-robinson** [kmansoft/clearview-linux#1]
Using the default install of clearview-server_0.2.0-5_amd64.deb, it does not create the `/var/lib/clearview-server/site/cv`directory, which causes the install to fail.

After creating this directory, by default the server looks for the static HTML files in `/var/lib/clearview/site/cv`rather than `/var/lib/clearview-server/site/cv` which causes all requests to return a 404.

Once `/usr/lib/systemd/system/clearview-server.service` is edited to add `-cvdir /var/lib/clearview-server/site/cv` to the end of the `ExecStart` line, it works.

**Comment by kmansoft** [comment]
Thank you.

Both issues fixed in 0.2.0-6: https://clearview.rocks/download.html

**Comment by tm-robinson** [comment]
Thanks!  Just updated to the new `clearview-server` .deb and confirmed this is fixed as well.
