### ISSUE TITLE
Only some data displayed or received (no graphs/meters)

### ISSUE THREAD

**Issue by todoneunl** [kmansoft/clearview-linux#2]
I have successfully installed the server, agent and the Android app. After I add a node I only see some data under disk, process and system (in both the web app and android app). It seems that all 'live' data, like graphs and meters, are not shown.

The only error I get with `journalctl -u clearview-server -f` is:

```
Directory: /cv/agent/v1
onAgentV1Add
clearview-server[28728]: Write error: {"code":"unauthorized","message":"unauthorized access"}
```

No relevant errors with `journalctl -u clearview-agent -f`:

`Cannot get http response data: Get "https://127.0.0.1/nginx_status": x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs`

Clearview version 0.2.0-7
Running on Debian 11.7

**Comment by kmansoft** [comment]
Regarding the write error and missing data - does the message repeat? How often?

Maybe it doesn't have permission to access influxdb? The default uri is `http://localhost:8086` - i.e. no username or password.

If needed, you can add `--influx-db-uri ...` to the server startup parameters in `clearview-server.service`

Second, regarding the nginx certificate error - ClearView Agent connects to `http://127.0.0.1/nginx_status` - i.e. not https but plain http - so I'm guessing your server as an http to https redirect which is enabled even for `127.0.0.1` (which is what's causing the error).

**Comment by todoneunl** [comment]
Thanks for your reply. To be honest, I found another monitoring tool. So I can't test it. I will close this issue.
